---
title: "Relative Biomass and Phosphorus Stress Factor"
author: "MD"
date: "'r format(Sys.time(), '%b %d, %Y')'"
output: 
 html_document:
   toc: true
   toc_float: true
   editor_options:
     chunk_output_type: console
   chunck_output_type: console
   chunk_output_type: console
---

```{r}
library(tidyverse)
library(emmeans)
library(RColorBrewer)
library(car)
library(agricolae)
```

# Read in Data

```{r}
d <- read.csv('../Data/inputs/Biomass.csv') %>% 
  filter(., !Sterility=='?') 
d$Condition <- gsub(' ','',d$Condition)
d$Fertilization <- gsub('FF','Fertilized_Fertilized',d$Fertilization)
d$Fertilization <- gsub('UF','Unfertilized_Fertilized',d$Fertilization)
d$Fertilization <- gsub('FU','Fertilized_Unfertilized',d$Fertilization)
d$Fertilization <- gsub('UU','Unfertilized_Unfertilized',d$Fertilization)

d <- d %>%
mutate(Condition = as_factor(Condition)) %>%
mutate(Condition = fct_relevel(Condition, "Wild", "Modern", "No_Plant"))
table(d$Condition)
d <- d %>%
mutate(Fertilization = as_factor(Fertilization)) %>%
mutate(Fertilization = fct_relevel(Fertilization, "Unfertilized_Unfertilized", "Fertilized_Unfertilized", "Unfertilized_Fertilized",  "Fertilized_Fertilized"))
table(d$Fertilization)

shoot <- filter(d, Type=='Shoot')
root <- filter(d, Type == 'Root')
par(mfrow=c(2,2))

```

# Shoot Biomass

## Model

### Shoot
```{r}
mod <- lm(Biomass_g ~ Sterility*Fertilization*Condition, data = shoot)
plot(mod)
Anova(mod, type = 3)
emmip(mod, Condition ~ Sterility | Fertilization, CIs = TRUE, type = "response")# type = response shows backtransformed 

emmeans(mod, pairwise ~ Condition|Fertilization|Sterility)

# emmeans(mod, ~ Fertilization*Domestication*Harvest)

emmeans(mod, ~ Condition*Fertilization*Sterility, type = "response")
df <- as.data.frame(emmeans(mod, ~ Condition*Fertilization*Sterility, type = "response"))

res <- emmeans(mod, list(pairwise ~ Condition*Fertilization*Sterility), adjust = "fdr")
plot(res[[1]], horizontal=T)
groups <- data.frame(multcomp::cld(res[[1]], adjust='fdr', Letters=c("abcdefghijklmnopqrstuvwxy"), decreasing=T)) %>% 
  select(., Fertilization, Condition, Sterility, .group)
df <- inner_join(df,groups, by = c('Fertilization', 'Condition', 'Sterility'))

names(df)[names(df) == '.group'] <- 'letters'
df$letters <- gsub(' ','',df$letters)
```

```{r}
p <- ggplot(aes(x=Fertilization, y=emmean, fill = Condition), data = df) +
  geom_col(position = 'dodge') +
  geom_errorbar(position = position_dodge(0.9),width=0.25,alpha=0.5,
                aes(ymin = emmean-SE, ymax = emmean+SE))+
  scale_fill_manual(values = c('darkorange2','darkblue','yellow3'))+
  geom_text(aes(label = letters),position=position_dodge(0.9), vjust = -1, hjust = 0) +
  facet_wrap(~Sterility, ncol=2)+
  theme_classic()+
  labs(y="Shoot Biomass")+
  theme(legend.title = element_blank(),
        legend.position = 'right',
        axis.text = element_text(color='black'),
        axis.text.x = element_text(angle = 90),
        axis.title.x = element_blank());p
```

### Root
## Model
```{r}
mod <- lm((Biomass_g) ~ Sterility*Fertilization*Condition, data = root)
plot(mod)
Anova(mod, type = 3)
emmip(mod, Condition ~ Sterility | Fertilization, CIs = TRUE, type = "response")# type = response shows backtransformed 

emmeans(mod, pairwise ~ Condition|Fertilization|Sterility)

# emmeans(mod, ~ Fertilization*Domestication*Harvest)

emmeans(mod, ~ Condition*Fertilization*Sterility, type = "response")
df <- as.data.frame(emmeans(mod, ~ Condition*Fertilization*Sterility, type = "response"))

res <- emmeans(mod, list(pairwise ~ Condition*Fertilization*Sterility), adjust = "fdr")
plot(res[[1]], horizontal=T)
groups <- data.frame(multcomp::cld(res[[1]], adjust='fdr', Letters=c("abcdefghijklmnopqrstuvwxy"), decreasing=T)) %>% 
  select(., Fertilization, Condition, Sterility, .group)
df <- inner_join(df,groups, by = c('Fertilization', 'Condition', 'Sterility'))

names(df)[names(df) == '.group'] <- 'letters'
df$letters <- gsub(' ','',df$letters)
```

```{r}
p <- ggplot(aes(x=Fertilization, y=response, fill = Condition), data = df) +
  geom_col(position = 'dodge') +
  geom_errorbar(position = position_dodge(0.9),width=0.25,alpha=0.5,
                aes(ymin = response-SE, ymax = response+SE))+
  scale_fill_manual(values = c('darkorange2','darkblue','yellow3'))+
  geom_text(aes(label = letters),position=position_dodge(0.9), vjust = -1, hjust = 0) +
  facet_wrap(~Sterility, ncol=2)+
  theme_classic()+
  labs(y="Root Biomass")+
  theme(legend.title = element_blank(),
        legend.position = 'right',
        axis.text = element_text(color='black'),
        axis.text.x = element_text(angle = 90),
        axis.title.x = element_blank());p
```


```{r}



aov_mod <- aov(mod)
summary(aov_mod) 

t <- HSD.test(mod, "Condition");t
t <- HSD.test(mod, "Sterility");t
t <- HSD.test(mod, "Fertilization");t

e <- emmeans(mod, pairwise ~ Fertilization*Condition)
e.df <- as.data.frame(e$contrasts) %>% 
  filter(., p.value < 0.05) 
e.df

e <- emmeans(mod, pairwise ~ Fertilization*Condition*Sterility)
e.df <- as.data.frame(e$contrasts) %>% 
  filter(., p.value < 0.05) 
e.df



plot(e[[1]], horizontal=F)
groups <- data.frame(multcomp::cld(e[[1]], adjust='fdr', Letters=c("abcdefghijklmnopqrstuvwxy"), decreasing=T))
groups <- groups %>%
  arrange(Fertilization, Condition, Sterility)

```

## Graph

```{r}
sum_shoot <-summarise(group_by(shoot,Sterility, Fertilization, Condition),
  n = n(),
  mean = mean(Biomass_g),
  sd = sd(Biomass_g),
  se = sd/sqrt(n))

sum_sl <- left_join(sum_shoot,groups, by = c('Fertilization', 'Condition', 'Sterility'))

names(sum_sl)[names(sum_sl) == '.group'] <- 'letters'
sum_sl$letters <- gsub(' ','',sum_sl$letters)

p1<-ggplot(sum_sl, aes(Fertilization, mean, fill = Condition)) +
  facet_wrap(~Sterility)+
  geom_col(position = 'dodge') +
  geom_text(aes(label = letters),position=position_dodge(0.9), vjust = -0.5, hjust = -0.2) +
  scale_fill_brewer(palette = 'Paired', breaks=c("No_Plant","Wild","Modern")) +  
  labs(y='Dry Shoot Biomass (g)')+
  geom_errorbar(aes(ymin = mean-se, ymax = mean+se),position=position_dodge(0.9), width = .25)+
 theme(axis.text=element_text(size=14, colour = "black"), 
        axis.title=element_text(size=12,face="bold"),
        axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        axis.title.x = element_blank());p1
ggsave(plot=p1, '../Data/R_PPT_figs/shootbiomassa_S-F-C_interaction.png',height=6,width=10)
```

# Root Biomass

## Model

```{r}
mod <- lm(Biomass_g ~ Sterility*Fertilization*Condition, data = root)
plot(mod)

aov_mod <- aov(mod)
summary(aov_mod) 

t <- HSD.test(mod, "Condition");t
t <- HSD.test(mod, "Fertilization");t

e <- emmeans(mod, pairwise ~ Fertilization*Condition)
e.df <- as.data.frame(e$contrasts) %>% 
  filter(., p.value < 0.05) 


plot(e[[1]], horizontal=F)
groups <- data.frame(multcomp::cld(e[[1]], adjust='fdr', Letters=c("abcdefghijklmnopqrstuvwxy"), decreasing=T))
groups <- groups %>%
  arrange(Fertilization, Condition)

```

## Graph

```{r}
sum_root <-summarise(group_by(root,Sterility, Fertilization, Condition),
  n = n(),
  mean = mean(Biomass_g),
  sd = sd(Biomass_g),
  se = sd/sqrt(n))

sum_rl <- left_join(sum_root,groups, by = c('Fertilization', 'Condition'))

names(sum_rl)[names(sum_rl) == '.group'] <- 'letters'
sum_rl$letters <- gsub(' ','',sum_rl$letters)

p2<-ggplot(sum_rl, aes(Fertilization, mean, fill = Condition)) +
  facet_wrap(~Sterility)+
  geom_col(position = 'dodge') +
  geom_text(aes(label = letters),position=position_dodge(0.9), vjust = -0.5, hjust = -0.2) +
  scale_fill_brewer(palette = 'Paired', breaks=c("No_Plant","Wild","Modern")) +  
  labs(y='Dry Root Biomass (g)')+
  geom_errorbar(aes(ymin = mean-se, ymax = mean+se),position=position_dodge(0.9), width = .25)+
 theme(axis.text=element_text(size=14, colour = "black"), 
        axis.title=element_text(size=12,face="bold"),
        axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        axis.title.x = element_blank());p2
ggsave(plot=p2, '../Data/R_PPT_figs/rootbiomass.png',height=6,width=10)
```

# Root to shoot ratio

## Get data

```{r}
bio_wide <- pivot_wider(bio, names_from = Type, values_from = Biomass_g) %>% 
  mutate(., Ratio = Root/Shoot)
```

## Model

```{r}
mod <- lm(log(Ratio) ~ Sterility*Fertilization*Condition, data = bio_wide)
plot(mod)

aov_mod <- aov(mod)
summary(aov_mod) 
```

## Graph

```{r}
sum_rs <-summarise(group_by(bio_wide,Sterility, Fertilization, Condition),
  n = n(),
  mean = mean(Ratio),
  sd = sd(Ratio),
  se = sd/sqrt(n))

sum_rs$Condition <- gsub(' ','',sum_rs$Condition)

p3<-ggplot(sum_rs, aes(Fertilization, mean, fill = Condition)) +
  facet_wrap(~Sterility)+
  geom_col(position = 'dodge') +
  scale_fill_brewer(palette = 'Paired', breaks=c("No_Plant","Wild","Modern")) +  
  labs(y='Root-to-Shoot Ratio (g/g)')+
  geom_errorbar(aes(ymin = mean-se, ymax = mean+se),position=position_dodge(0.9), width = .25)+
 theme(axis.text=element_text(size=14, colour = "black"), 
        axis.title=element_text(size=12,face="bold"),
        axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        axis.title.x = element_blank());p3
ggsave(plot=p2, '../Data/R_PPT_figs/rootbiomass.png',height=6,width=10)
```
