---
title: "Olsen Phosphorus Concentration"
author: "MD"
date: "'r format(Sys.time(), '%b %d, %Y')'"
output: 
 html_document:
   toc: true
   toc_float: true
   editor_options:
     chunk_output_type: console
   chunck_output_type: console
   chunk_output_type: console
---

```{r}
library(patchwork)
library(tidyverse)
library(emmeans)
library(RColorBrewer)
library(car)
library(agricolae)
```

# Read in Data

```{r}
d <- read.csv('../Data/inputs/Olsen_P.csv') %>% 
  filter(!is.na(Olsen_ppm)) 
```

# Model Fitting

```{r}
par(mfrow=c(2,2))
mod <- lm(Olsen_ppm ~ Fertilization*soil.conditioning*Sterility, data = d)
plot(mod)
outlierTest(mod)

# d  <- op[-c(90),]
# mod <- lm(Olsen_ppm ~ Fertilization*soil.conditioning*Sterility, data = d)
# plot(mod)

aov.mod <- aov(mod)
summary(aov.mod)
t <- HSD.test(mod,"Fertilization");t

```

# Graph

```{r}
d.sum <-summarise(group_by(d,Sterility, Fertilization, soil.conditioning),
  n = n(),
  mean = mean(Olsen_ppm),
  sd = sd(Olsen_ppm),
  se = sd/sqrt(n)) %>% 
  arrange(., by=Fertilization) 
d.sum$letters<-c('a','a','a','a','a','a','c','c','c','c','c','c','b','b','b','b','b','b','d','d','d','d','d','d')


names(sum_rl)[names(sum_rl) == '.group'] <- 'letters'
sum_rl$letters <- gsub(' ','',sum_rl$letters)

p2<-ggplot(d.sum, aes(Fertilization, mean, fill = soil.conditioning)) +
  facet_wrap(~Sterility)+
  geom_col(position = 'dodge') +
  geom_text(aes(label = letters),position=position_dodge(0.9), vjust = -0.5, hjust = -0.2) +
  scale_fill_brewer(palette = 'Paired', breaks=c("No_Plant","Wild","Modern")) +  
  labs(y='Olsen P (mg/kg)')+
  geom_errorbar(aes(ymin = mean-se, ymax = mean+se),position=position_dodge(0.9), width = .25)+
 theme(axis.text=element_text(size=14, colour = "black"), 
        axis.title=element_text(size=12,face="bold"),
        axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        axis.title.x = element_blank());p2
ggsave(plot=p2, '../Data/R_PPT_figs/OlsenP.png',height=6,width=10)





sum_op<-summarise(group_by(d,Variety,Domestication,Fertilization),
  n = n(),
  mean = mean(Olsen_P),
  sd = sd(Olsen_P),
  se = sd/sqrt(n))

sum_op$letters <- c('cd','ab','bc','ab','ab','ab','cb','ab','d','ab','cd','ab','cd','ab','cd','ab','cd','ab','d','a','cd','b','cd','ab') #from emmeans contrasts above for Fertilization*Domestication*Variety

level_order <- factor(sum_op$Variety,level = c('LA0716',  'LA1580', 'LA1698', 'LA1519', 'Matchless', 'B Pink', 'Marglobe', 'Rutgers','Bobcat','Quali T','Line 1','Line 2'))
p<-ggplot(sum_op, aes(level_order, mean, fill = Domestication)) + 
  geom_col(position = 'dodge') +
  geom_text(aes(label = letters), vjust = -0.45, hjust = -0.28, size = 6) +
  facet_wrap(~Fertilization, scales = 'free', ncol=1)+
  labs(y='Olsen Phosphorus (mg/kg)')+
  geom_errorbar(aes(ymin = mean-se, 
                    ymax = mean+se),
                position=position_dodge(0.9), width = .25)+
  scale_fill_brewer(palette = 'Paired')+
  theme(axis.text.x=element_text(size=14, colour = "black", angle = 90), 
        axis.text.y=element_text(size=14, colour = "black"),
        axis.title=element_text(size=16,face="bold"),
        axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        strip.text.y = element_text(size=8, face="bold"), 
        legend.position = 'none',
        strip.text = element_blank(),
        strip.background = element_blank(),
        axis.title.x = element_blank());p


ggsave(plot=p, filename = 'Data/Outputs/Figures/Figure3.pdf', width = 12, height = 10)

```

